title: About Me
author: Prabhat Mishra
theme: minima
email: prabhatm12345@gmail.cm
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Prabhat. I'm soon to graduate from East Brunswick High School. I'll be attending PennState this fall with the intent of majoring in Computer Science.

# social links
github_username:  PrabhatM14
instagram_username: Prxbhxt
snapchat_username: Prxbhxt04

show_excerpts: true # set to false to remove excerpts on the homepage
