title: About Me
author: Prabhat Mishra
theme: minima
email: prabhatm12345@gmail.cm

# social links
github_username:  PrabhatM14
instagram_username: Prxbhxt
snapchat_username: Prxbhxt04

show_excerpts: true # set to false to remove excerpts on the homepage
